# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Draft_MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Image_Resource_rc


class UI_Home(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(UI_Home, self).__init__(parent)
        self.setObjectName("Home")
        self.resize(1000, 800)

        self.centralwidget = QtWidgets.QWidget(self)
        palette = self.centralwidget.palette()
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(QtGui.QPixmap(":/Images/openart-image_ebcLOSxf_1741845947928_raw.jpg")))

        self.centralwidget.setPalette(palette)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 390, 751, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.Start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Start.setIconSize(QtCore.QSize(16, 16))
        self.Start.setObjectName("Start")
        self.verticalLayout.addWidget(self.Start)

        self.Settings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Settings.setObjectName("Settings")
        self.verticalLayout.addWidget(self.Settings)

        self.Exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Exit.setObjectName("Exit")
        self.verticalLayout.addWidget(self.Exit)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Home"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.Settings.setText(_translate("MainWindow", "Settings"))
        self.Exit.setText(_translate("MainWindow", "Exit"))

