# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Draft_MapPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import Map_Resource_rc  # Import the resource file if required

class UI_Map(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(UI_Map, self).__init__(parent)
        self.resize(800, 600)

        # Set up the background image
        self.setAutoFillBackground(True)
        palette = self.palette()
        pixmap = QtGui.QPixmap(":/MapImg/map_image.png")
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(pixmap))
        self.setPalette(palette)

        # Retranslate and update window title
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Map"))

